### ISSUE TITLE
checkpoint运行错误

### ISSUE THREAD

**Issue by Jhin3433** [zhufq00/mcnc#3] opened 2023-07-25 13:27 UTC
你好，上传的最优checkpoint运行报以下错误：
```shell
Exception has occurred: RuntimeError
[enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
  File "/sdc/wwc/mcnc-main/code/main_align.py", line 343, in <module>
    checkpoint = torch.load(args.checkpoint)
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by zhufq00** [comment] 2023-07-27 06:43
The file may be truncated for some strange reason, I can't find other checkpoints on my current machine, if you have a problem with the reproduction process, we can discuss it.

**Comment by zhufq00** [comment] 2023-09-15 08:23
Since we have discussed this issue privately, I am closing it here.

**Closed as completed** 2023-09-15 08:24 UTC
